<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Explore projects' => '发现',
    'Logout' => '退出',
    'About' => '关于我们',
    'Bookmarks' => '书签',
    'Don\'t have an account? {signUpLink}' => '还没有账号? {signUpLink}',
    'Email' => '电邮',
    'If you forgot your password you can {reset_it}.' => '忘记密码 {reset_it}.',
    'Linked {client} account.' => '{client} 账号绑定.',
    'Login' => '登陆',
    'Password' => '密码',
    'Please choose your new password:' => '请输入你的新密码:',
    'Please fill out your email. A link to reset password will be sent there.' => '请填写你的电子邮件。重置密码的链接将被发送到那里。',
    'RSS feed' => 'RSS',
    'Request password reset' => '请求重置密码',
    'Reset password' => '重置密码',
    'Save' => '保存',
    'Send' => '发送',
    'Sign in with {service}' => '使用 {service}登陆',
    'Sign up!' => '注册!',
    'Signup' => '注册',
    'Social network {client} has been successfully disabled.' => '{client} 已停用.',
    'This email address has already been taken.' => '此电子邮件地址已被占用.',
    'This username has already been taken.' => '此用户名已被占用.',
    'Unable to link {client} account. There is another user using it.' => '无法绑定{client}帐户.另一个用户正在使用它.',
    'Unable to link {client} account: {errors}' => '无法绑定{client}帐户：{errors}',
    'Unable to save user: {errors}' => '无法保存用户：{errors}',
    'Unable to save {client} account: {errors}' => '无法保存{client} 帐户：{errors}',
    'Unknown' => '未知',
    'User name' => '用户名',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => '与{client}帐户中具有相同电子邮件的用户已存在,但未绑定到该用户.请使用该电子邮件登录后绑定它.',
    'Username' => '用户名',
    'or' => '或',
    'reset it' => 'восстановить его',
];
