<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created At' => '创建时间',
    'Created By' => '创建人',
    'ID' => 'ID',
    'Status' => '状态',
    'Updated At' => '更新时间',
    'User contributed notes' => '用户维护到注释',
    'at {time}' => '于 {time}',
    'Leave a comment' => '去评论',
    'Comment' => '评论',
    '{loginLink} or {signupLink} to post comments.' => '{loginLink} 或 {signupLink}, 去发表评论.',
    'Login' => '登陆',
    'signup' => '注册',
    'Text' => '内容',
    'Delete' => '删除',
    'Are you sure you want to delete this comment?' => '是否确实要删除此评论?',
    'Comment deleted.' => '评论删除成功.',
    'Failed to delete comment.' => '评论删除失败.',
    'You can not delete this comment.' => '您不能删除此评论.',
];
