<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Any Status' => '全部状态',
    'Add project' => '发布项目',
    'After the image upload, you will be able to crop it.' => '上传图像后, 您将能够对其进行裁剪.',
    'Any Yii version' => '任意 Yii 版本',
    'Any code access' => '任意代码访问',
    'Apply' => '使用',
    'Approve' => '审核',
    'Are you sure you want to delete this image?' => '是否确实要删除此图像?',
    'Are you sure you want to delete this project?' => '是否确实要删除此项目?',
    'Back' => '后退',
    'Cancel' => '取消',
    'Content' => '内容',
    'Created At' => '创建时间',
    'Created By' => '创建人',
    'Delete' => '删除',
    'Delete image' => '删除图片',
    'Deleted' => '已删除',
    'Description in {language}' => '{language}介绍',
    'Draft' => '草稿',
    'Failed to delete project.' => '删除项目失败.',
    'Failed to update project.' => '更新项目失败.',
    'Featured projects' => '推荐项目',
    'Filters' => '筛选',
    'General' => '基本信息',
    'General info' => '基本信息',
    'ID' => 'ID',
    'Is Featured' => '推荐',
    'Is OpenSource' => '开源项目',
    'Language' => '语言',
    'Made one? Share it!' => '做了一个? 分享吧!',
    'Manage projects' => '管理项目',
    'Mark as primary image' => '用作主图',
    'New projects' => '新项目',
    'Next' => '下一页',
    'Not open source' => '不是开源项目',
    'Only Featured' => '推荐',
    'Open source' => '开源项目',
    'OpenSource' => '开源项目',
    'Please, upload some screenshots to make your project look nice.' => '上传图片.',
    'Preview & Approve' => '预览 & 审核',
    'Primary image' => '主图',
    'Project ID' => '项目 ID',
    'Project added!' => '添加项目成功!',
    'Project deleted.' => '删除项目成功.',
    'Projects' => '项目',
    'Projects built with Yii' => '搜罗天下高质量网站',
    'Publish' => '发布',
    'Published' => '发布',
    'Re-crop image' => '重新编辑图片',
    'Save as draft' => '保存为草稿',
    'Screenshots' => '截屏',
    'Slug' => 'Slug',
    'Source Code' => '源码',
    'Source URL' => '源码地址',
    'Status' => '状态',
    'Tag ID' => '标签 ID',
    'Tags' => '标签',
    'The project has been moved to draft.' => '该项目已移至草稿.',
    'Title' => '标题',
    'Top {n}' => 'Top {n}',
    'Top {n} projects is still empty' => ' Top {n} 项目不存在',
    'URL' => 'URL',
    'Unknown' => '未知',
    'Update' => '更新',
    'Update project {title}' => '更新项目标题 {title}',
    'Updated At' => '更新时间',
    'Updated By' => '更新人',
    'Updated: ' => '已经更新:',
    'Upload' => '上传',
    'Upload an image' => '上传一张图片',
    'Upload screenshots' => '上传截屏',
    'User ID' => '用户 ID',
    'View  {n, plural, one{one more project} other{# more projects}}' => '浏览 {n, plural, one{# 更多项目} few{# 更多项目} many{# 更多项目} other{# 更多项目}}',
    'Yii Version' => 'Yii 版本',
    'You can not delete this project.' => '不能删除此项目.',
    'You can not restore a deleted project.' => '无法恢复已删除的项目.',
    'You can not update this project.' => '不能更新此项目.',
    'You can only delete a project from a draft.' => '只能从草稿中删除项目.',
    'You can upload up to 5 images. The first image will be used as a main preview of your project, while others will be displayed on the project details page' => '你最多可以上传5张图片. 第一个图像将用作项目的主预览, 而其他图像将显示在项目详细信息页面上.',
    'You have no bookmarked projects yet.' => '你还没有书签项目.',
    '{n, plural, one{# project} other{# projects}} made with {link}' => '{n,plural,one{# 项目} few{# 项目} many{# 项目} other{# 项目}} 基于 {link}',
    'You did not save the image. Are you sure you want to continue?' => '您没有保存图像. 确定要继续吗?',
];
