<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Update user {username}: ' => '更新用户 {username}:',
    'Active' => '激活',
    'Are you sure you want to delete this item?' => '是否确实要删除此项目?',
    'Auth Key' => '授权密钥',
    'Avatar' => '头像',
    'Can not save your profile.' => '无法保存您的个人资料.',
    'Connect with {servicename}' => '与 {servicename}链接',
    'Create' => '创建',
    'Created At' => '创建时间',
    'Current avatar' => '当前头像',
    'Delete' => '删除',
    'Email' => '电邮',
    'Facebook' => 'Facebook',
    'Fullname' => '全名',
    'Github' => 'Github',
    'Haven\'t added any projects yet.' => '尚未添加任何项目.',
    'ID' => 'ID',
    'Incorrect username or password.' => '无效的用户名或密码.',
    'Manage users' => '用户管理',
    'Password Hash' => '密码',
    'Password Reset Token' => '重置密码口令',
    'Status' => '状态',
    'Twitter' => 'Twitter',
    'Update' => '更新',
    'Updated At' => '更新时间',
    'Username' => '用户名',
    'Users' => '用户',
    'You can not update this user.' => '无法更新此用户.',
    'Your profile has been successfully updated.' => '您的配置文件已成功更新.',
    'Notify about new comments by e-mail' => '通过电子邮件发送评论通知',
];
